### ISSUE TITLE
fix labels for a subset of actigraphy var

### ISSUE THREAD

**Issue by yzhang104** [nsrr/mesa-data-dictionary#22]
Change the label roots from "avgeffsp" to "avgmefsp" for avgmainteff5, avgmainteffnw5, avgmainteffwd5, avgmainteffwe5, avgmainteffwo5.
Change the label roots  from "avgeffrt" to "avgeffsp" for avgefficiency5, avgefficiencynw5, avgefficiencywd5, avgefficiencywe5, avgefficiencywo5.
Change any rest related root: XXXXXXrt_ to XXXXXXrs_

**Comment by mrueschman** [comment]
Closed in c52a711
